//! Raw, lossless clipboard access.
//!
//! A single copy is not one piece of data: the source app puts the same
//! content on the clipboard in several *formats* at once (plain text, RTF,
//! HTML, PNG, its own private formats, ...) and the app you paste into picks
//! the richest one it understands. To make a restored clip paste exactly like
//! the original, Cliplog saves every format as opaque bytes and writes all of
//! them back. It only interprets a few well-known ones (text, file lists,
//! images) to show a preview.
//!
//! - macOS: the pasteboard holds one or more *items* (copying 3 files in
//!   Finder gives 3 items), each with data for several UTI types such as
//!   `public.utf8-plain-text`. Format names here are those UTIs.
//! - Windows: the clipboard holds one set of formats. Standard formats are
//!   stored as `#<id>` (e.g. `#13` = CF_UNICODETEXT); app-registered formats
//!   by their registered name (e.g. `HTML Format`), because registered ids
//!   differ between sessions.
//!
//! Known limitations (also in the README):
//! - **Copied files are references, not contents.** Copying a file in
//!   Finder/Explorer puts its *path* on the clipboard. If the file is later
//!   moved, renamed or deleted, pasting that clip will fail or paste nothing.
//! - Some formats only make sense while the source app is still running (OLE
//!   objects on Windows, file promises on macOS). Those are skipped.
//! - Content marked as secret by password managers is never recorded (see
//!   `MAC_EXCLUDE_MARKERS` / `WIN_EXCLUDE_MARKERS`).
//! - A single format bigger than `MAX_FORMAT_BYTES` is dropped.

use serde::{Deserialize, Serialize};
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

/// Formats larger than this are not saved.
pub const MAX_FORMAT_BYTES: usize = 100 * 1024 * 1024;

pub const MAC_TEXT: &str = "public.utf8-plain-text";
pub const MAC_FILE_URL: &str = "public.file-url";
const MAC_IMAGES: &[&str] = &["public.png", "public.tiff", "public.jpeg", "com.compuserve.gif"];
pub const WIN_UNICODE_TEXT: &str = "#13";
const WIN_HDROP: &str = "#15";
const WIN_IMAGES: &[&str] = &["#8", "#17", "PNG"];

/// Markers that password managers and similar apps add to say "don't record
/// this". See http://nspasteboard.org.
#[allow(dead_code)]
const MAC_EXCLUDE_MARKERS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
];
#[allow(dead_code)]
const WIN_EXCLUDE_MARKERS: &[&str] = &[
    "ExcludeClipboardContentFromMonitorProcessing",
    "Clipboard Viewer Ignore",
];

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct Format {
    pub name: String,
    #[serde(with = "base64_bytes")]
    pub data: Vec<u8>,
}

/// Everything that was on the clipboard for one copy. `items` has one entry
/// per pasteboard item on macOS and exactly one entry on Windows.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct Snapshot {
    pub items: Vec<Vec<Format>>,
}

impl Snapshot {
    fn formats(&self) -> impl Iterator<Item = &Format> {
        self.items.iter().flatten()
    }

    fn find(&self, name: &str) -> Option<&Format> {
        self.formats().find(|f| f.name == name)
    }

    pub fn total_bytes(&self) -> usize {
        self.formats().map(|f| f.data.len()).sum()
    }

    pub fn hash(&self) -> u64 {
        let mut h = DefaultHasher::new();
        for item in &self.items {
            item.len().hash(&mut h);
            for f in item {
                f.name.hash(&mut h);
                f.data.hash(&mut h);
            }
        }
        h.finish()
    }

    /// The plain-text form of the clip, if it has one.
    pub fn text(&self) -> Option<String> {
        let mac: Vec<String> = self
            .items
            .iter()
            .filter_map(|item| item.iter().find(|f| f.name == MAC_TEXT))
            .filter_map(|f| String::from_utf8(f.data.clone()).ok())
            .collect();
        if !mac.is_empty() {
            return Some(mac.join("\n"));
        }
        self.find(WIN_UNICODE_TEXT).map(|f| utf16_until_nul(&f.data))
    }

    /// Paths of copied files, if this is a file copy.
    pub fn files(&self) -> Vec<String> {
        let mac: Vec<String> = self
            .formats()
            .filter(|f| f.name == MAC_FILE_URL)
            .filter_map(|f| std::str::from_utf8(&f.data).ok().and_then(file_url_to_path))
            .collect();
        if !mac.is_empty() {
            return mac;
        }
        self.find(WIN_HDROP).map(|f| parse_hdrop(&f.data)).unwrap_or_default()
    }

    pub fn has_image(&self) -> bool {
        self.formats()
            .any(|f| MAC_IMAGES.contains(&f.name.as_str()) || WIN_IMAGES.contains(&f.name.as_str()))
    }

    /// True if the only thing on the clipboard is plain text, so it can be
    /// restored from the text alone without storing the raw bytes.
    pub fn is_plain_text_only(&self) -> bool {
        self.formats().all(|f| f.name == MAC_TEXT || f.name == WIN_UNICODE_TEXT)
    }

    /// Keeps only the plain-text formats (used when a clip is too big).
    pub fn retain_text(&mut self) {
        for item in &mut self.items {
            item.retain(|f| f.name == MAC_TEXT || f.name == WIN_UNICODE_TEXT);
        }
        self.items.retain(|i| !i.is_empty());
    }

    /// Compact binary encoding used for clips stored in their own file.
    pub fn encode(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(self.total_bytes() + 64);
        out.extend_from_slice(b"CLP1");
        out.extend_from_slice(&(self.items.len() as u32).to_le_bytes());
        for item in &self.items {
            out.extend_from_slice(&(item.len() as u32).to_le_bytes());
            for f in item {
                out.extend_from_slice(&(f.name.len() as u32).to_le_bytes());
                out.extend_from_slice(f.name.as_bytes());
                out.extend_from_slice(&(f.data.len() as u64).to_le_bytes());
                out.extend_from_slice(&f.data);
            }
        }
        out
    }

    pub fn decode(bytes: &[u8]) -> Option<Self> {
        let mut r = Reader(bytes);
        if r.take(4)? != b"CLP1" {
            return None;
        }
        let mut items = Vec::new();
        for _ in 0..r.u32()? {
            let mut item = Vec::new();
            for _ in 0..r.u32()? {
                let name_len = r.u32()? as usize;
                let name = String::from_utf8(r.take(name_len)?.to_vec()).ok()?;
                let data_len = r.u64()? as usize;
                item.push(Format { name, data: r.take(data_len)?.to_vec() });
            }
            items.push(item);
        }
        Some(Snapshot { items })
    }
}

struct Reader<'a>(&'a [u8]);

impl<'a> Reader<'a> {
    fn take(&mut self, n: usize) -> Option<&'a [u8]> {
        if self.0.len() < n {
            return None;
        }
        let (head, tail) = self.0.split_at(n);
        self.0 = tail;
        Some(head)
    }
    fn u32(&mut self) -> Option<u32> {
        Some(u32::from_le_bytes(self.take(4)?.try_into().ok()?))
    }
    fn u64(&mut self) -> Option<u64> {
        Some(u64::from_le_bytes(self.take(8)?.try_into().ok()?))
    }
}

fn utf16_until_nul(bytes: &[u8]) -> String {
    let units: Vec<u16> = bytes
        .chunks_exact(2)
        .map(|c| u16::from_le_bytes([c[0], c[1]]))
        .take_while(|&u| u != 0)
        .collect();
    String::from_utf16_lossy(&units)
}

fn file_url_to_path(url: &str) -> Option<String> {
    let rest = url.trim_end_matches('\0').strip_prefix("file://")?;
    let rest = rest.strip_prefix("localhost").unwrap_or(rest);
    let bytes = rest.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let Ok(b) = u8::from_str_radix(std::str::from_utf8(&bytes[i + 1..i + 3]).ok()?, 16) {
                out.push(b);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    let path = String::from_utf8(out).ok()?;
    Some(path.trim_end_matches('/').to_string())
}

/// Parses a Windows CF_HDROP (DROPFILES struct followed by a list of
/// NUL-separated paths).
fn parse_hdrop(bytes: &[u8]) -> Vec<String> {
    let u32_at = |i: usize| bytes.get(i..i + 4).map(|b| u32::from_le_bytes(b.try_into().unwrap()));
    let (Some(offset), Some(wide)) = (u32_at(0), u32_at(16)) else { return Vec::new() };
    let Some(list) = bytes.get(offset as usize..) else { return Vec::new() };
    let joined = if wide != 0 {
        let units: Vec<u16> = list.chunks_exact(2).map(|c| u16::from_le_bytes([c[0], c[1]])).collect();
        String::from_utf16_lossy(&units)
    } else {
        String::from_utf8_lossy(list).into_owned()
    };
    joined.split('\0').take_while(|s| !s.is_empty()).map(String::from).collect()
}

mod base64_bytes {
    use base64::Engine;
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(data: &[u8], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&base64::engine::general_purpose::STANDARD.encode(data))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = String::deserialize(d)?;
        base64::engine::general_purpose::STANDARD
            .decode(s)
            .map_err(serde::de::Error::custom)
    }
}

// ---------- macOS ----------

#[cfg(target_os = "macos")]
mod platform {
    use super::*;
    use objc2::rc::{autoreleasepool, Retained};
    use objc2::runtime::ProtocolObject;
    use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardWriting};
    use objc2_foundation::{NSArray, NSData, NSString};

    /// Types that are system-generated aliases of other types, or promises
    /// that can't be fulfilled once the source app is gone.
    fn skip_type(name: &str) -> bool {
        name.starts_with("com.apple.pasteboard.promised")
            || name.starts_with("com.apple.NSFilePromise")
            || name == "NSPromiseContentsPboardType"
            || name.starts_with("CorePasteboardFlavorType")
            || name.starts_with("Apple ")
            || (name.starts_with("NS") && name.ends_with("PboardType"))
    }

    pub fn change_count() -> Option<u32> {
        autoreleasepool(|_| Some(NSPasteboard::generalPasteboard().changeCount() as u32))
    }

    pub fn read() -> Result<Option<Snapshot>, String> {
        autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            // Check for "don't record" markers before reading any data.
            if let Some(types) = pb.types() {
                if types.iter().any(|t| MAC_EXCLUDE_MARKERS.contains(&t.to_string().as_str())) {
                    return Ok(None);
                }
            }
            let Some(items) = pb.pasteboardItems() else { return Ok(None) };
            let mut snapshot = Snapshot::default();
            for item in items.iter() {
                let mut formats = Vec::new();
                for ty in item.types().iter() {
                    let name = ty.to_string();
                    if skip_type(&name) {
                        continue;
                    }
                    if let Some(data) = item.dataForType(&ty) {
                        if data.len() <= MAX_FORMAT_BYTES {
                            formats.push(Format { name, data: data.to_vec() });
                        }
                    }
                }
                if !formats.is_empty() {
                    snapshot.items.push(formats);
                }
            }
            Ok((!snapshot.items.is_empty()).then_some(snapshot))
        })
    }

    pub fn write(snapshot: &Snapshot) -> Result<(), String> {
        autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            let objects: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = snapshot
                .items
                .iter()
                .map(|formats| {
                    let item = NSPasteboardItem::new();
                    for f in formats {
                        item.setData_forType(&NSData::with_bytes(&f.data), &NSString::from_str(&f.name));
                    }
                    ProtocolObject::from_retained(item)
                })
                .collect();
            pb.clearContents();
            if pb.writeObjects(&NSArray::from_retained_slice(&objects)) {
                Ok(())
            } else {
                Err("macOS refused the clipboard data".into())
            }
        })
    }
}

// ---------- Windows ----------

#[cfg(target_os = "windows")]
mod platform {
    use super::*;
    use clipboard_win::{raw, Clipboard};

    const CF_TEXT: u32 = 1;
    const CF_OEMTEXT: u32 = 7;
    const CF_DIB: u32 = 8;
    const CF_UNICODETEXT: u32 = 13;
    const CF_LOCALE: u32 = 16;
    const CF_DIBV5: u32 = 17;

    /// Formats that are GDI handles rather than memory, that Windows
    /// synthesizes from another format, or OLE formats that point into the
    /// source process.
    fn skip_format(id: u32, name: &str, all: &[u32]) -> bool {
        matches!(id, 2 | 3 | 9 | 14 | 0x80 | 0x82 | 0x83 | 0x8E | 0x200..=0x3FF)
            || (matches!(id, CF_TEXT | CF_OEMTEXT | CF_LOCALE) && all.contains(&CF_UNICODETEXT))
            || (id == CF_DIB && all.contains(&CF_DIBV5))
            || matches!(
                name,
                "DataObject" | "Ole Private Data" | "Object Descriptor" | "Link Source Descriptor"
                    | "Link Source" | "Embed Source" | "OwnerLink" | "ObjectLink" | "Native"
            )
    }

    fn name_of(id: u32) -> Option<String> {
        if id < 0xC000 {
            Some(format!("#{id}"))
        } else {
            raw::format_name_big(id)
        }
    }

    fn id_of(name: &str) -> Option<u32> {
        match name.strip_prefix('#') {
            Some(n) => n.parse().ok(),
            None => raw::register_format(name).map(|n| n.get()),
        }
    }

    pub fn change_count() -> Option<u32> {
        raw::seq_num().map(|n| n.get())
    }

    pub fn read() -> Result<Option<Snapshot>, String> {
        let _guard = Clipboard::new_attempts(10).map_err(|e| e.to_string())?;
        let ids: Vec<u32> = raw::EnumFormats::new().collect();
        let named: Vec<(u32, String)> = ids.iter().filter_map(|&id| Some((id, name_of(id)?))).collect();

        for (id, name) in &named {
            if WIN_EXCLUDE_MARKERS.contains(&name.as_str()) {
                return Ok(None);
            }
            // Windows' own clipboard history flag: a DWORD of 0 means "don't keep".
            if name == "CanIncludeInClipboardHistory" {
                let mut v = Vec::new();
                if raw::get_vec(*id, &mut v).is_ok() && v.get(..4) == Some(&[0, 0, 0, 0]) {
                    return Ok(None);
                }
            }
        }

        let mut formats = Vec::new();
        for (id, name) in named {
            if skip_format(id, &name, &ids) {
                continue;
            }
            let mut data = Vec::new();
            if raw::get_vec(id, &mut data).is_ok() && !data.is_empty() && data.len() <= MAX_FORMAT_BYTES {
                formats.push(Format { name, data });
            }
        }
        if formats.is_empty() {
            return Ok(None);
        }
        Ok(Some(Snapshot { items: vec![formats] }))
    }

    pub fn write(snapshot: &Snapshot) -> Result<(), String> {
        let _guard = Clipboard::new_attempts(10).map_err(|e| e.to_string())?;
        raw::empty().map_err(|e| e.to_string())?;
        for f in snapshot.items.iter().flatten() {
            if let Some(id) = id_of(&f.name) {
                let _ = raw::set_without_clear(id, &f.data);
            }
        }
        Ok(())
    }
}

// ---------- other platforms (text only, handled by the caller) ----------

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
mod platform {
    use super::*;

    pub fn change_count() -> Option<u32> {
        None
    }

    pub fn read() -> Result<Option<Snapshot>, String> {
        Err("raw clipboard access is not supported on this platform".into())
    }

    pub fn write(_: &Snapshot) -> Result<(), String> {
        Err("raw clipboard access is not supported on this platform".into())
    }
}

pub use platform::{change_count, read, write};

/// Whether `read`/`write` work on this platform.
pub const SUPPORTED: bool = cfg!(any(target_os = "macos", target_os = "windows"));

#[cfg(test)]
mod tests {
    use super::*;

    fn fmt(name: &str, data: &[u8]) -> Format {
        Format { name: name.into(), data: data.to_vec() }
    }

    #[test]
    fn encode_decode_roundtrip() {
        let s = Snapshot {
            items: vec![
                vec![fmt(MAC_TEXT, b"hello"), fmt("public.html", b"<b>hello</b>")],
                vec![fmt(MAC_FILE_URL, b"file:///tmp/a%20b.txt")],
            ],
        };
        assert_eq!(Snapshot::decode(&s.encode()), Some(s.clone()));
        assert_eq!(Snapshot::decode(b"nope"), None);
        let json = serde_json::to_string(&s).unwrap();
        assert_eq!(serde_json::from_str::<Snapshot>(&json).unwrap(), s);
    }

    #[test]
    fn previews() {
        let s = Snapshot {
            items: vec![vec![fmt(MAC_FILE_URL, b"file:///Users/me/My%20Report.pdf")], vec![fmt(MAC_FILE_URL, b"file:///tmp/dir/")]],
        };
        assert_eq!(s.files(), ["/Users/me/My Report.pdf", "/tmp/dir"]);

        let wide: Vec<u8> = "héllo\0junk".encode_utf16().flat_map(|u| u.to_le_bytes()).collect();
        let w = Snapshot { items: vec![vec![fmt(WIN_UNICODE_TEXT, &wide), fmt("PNG", b"x")]] };
        assert_eq!(w.text().as_deref(), Some("héllo"));
        assert!(w.has_image());
        assert!(!w.is_plain_text_only());

        let mut hdrop = vec![20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0];
        hdrop.extend("C:\\a.txt\0C:\\b\0\0".encode_utf16().flat_map(|u| u.to_le_bytes()));
        let h = Snapshot { items: vec![vec![fmt(WIN_HDROP, &hdrop)]] };
        assert_eq!(h.files(), ["C:\\a.txt", "C:\\b"]);
    }

    /// Writes to and reads from the real clipboard, so it's opt-in:
    /// `cargo test -- --ignored`.
    #[test]
    #[ignore]
    fn real_clipboard_roundtrip() {
        if !SUPPORTED {
            return;
        }
        let name = if cfg!(target_os = "macos") { MAC_TEXT } else { WIN_UNICODE_TEXT };
        let text: Vec<u8> = if cfg!(target_os = "macos") {
            b"cliplog roundtrip".to_vec()
        } else {
            "cliplog roundtrip\0".encode_utf16().flat_map(|u| u.to_le_bytes()).collect()
        };
        let custom = if cfg!(target_os = "macos") { "com.example.cliplog-test" } else { "Cliplog Test Format" };
        let s = Snapshot { items: vec![vec![fmt(name, &text), fmt(custom, b"\x00\x01private")]] };
        write(&s).unwrap();
        let back = read().unwrap().unwrap();
        assert_eq!(back.text().as_deref(), Some("cliplog roundtrip"));
        assert!(back.items[0].iter().any(|f| f.name == custom && f.data == b"\x00\x01private"));
    }
}
